### ISSUE TITLE
[Your Device] is busy: Preparing debugger support for [Your Device]

### ISSUE THREAD

**Issue by NoodleOfDeath** [sauravexodus/xcode-9-ios-12-support#1]
I am getting the following error message in Xcode after downloading and running your bash script: 
![image](https://user-images.githubusercontent.com/14790443/47189319-eed67a80-d309-11e8-8256-504c4ce83073.png)

**Comment by sauravexodus** [comment]
Xcode is preparing support files for your device. This is very common and not an issue. 
Let me know if you need further assistance.

Closing the issue for now :)
