### ISSUE TITLE
Question: Will this package work for xcode 10?

### ISSUE THREAD

**Issue by ronaldso55** [sauravexodus/xcode-9-ios-12-support#4]
See subject line.

**Comment by gingerbeardman** [comment]
Yes, it does. I just used it to build to an iOS 12.3.1 device using Xcode 10.1

If you look at [install.sh](https://github.com/sauravexodus/xcode-9-ios-12-support/blob/master/install.sh) you'll see that it simply copies the support files in this repo (all taken from the latest Xcode) into your existing /Applications/Xcode.app and makes no check for version.

So I think, at this point in time, the name of the repo is a little misleading.

**Comment by sauravexodus** [comment]
It should. Let me know if it works for you. I'll go ahead and close this then @gingerbeardman

> Yes, it does. I just used it to build to an iOS 12.3.1 device using Xcode 10.1
> 
> If you look at [install.sh](https://github.com/sauravexodus/xcode-9-ios-12-support/blob/master/install.sh) you'll see that it simply copies the support files in this repo (all taken from the latest Xcode) into your existing /Applications/Xcode.app and makes no check for version.
> 
> So I think, at this point in time, the name of the repo is a little misleading.
